#!/usr/bin/env bash


pushd docker/dnastack-client-library || exit
    docker build --no-cache -t "gcr.io/dnastack-pub-container-store/dnastack-client-library:$(git describe)" .
    docker tag "gcr.io/dnastack-pub-container-store/dnastack-client-library:$(git describe)" gcr.io/dnastack-pub-container-store/dnastack-client-library:latest
    docker push "gcr.io/dnastack-pub-container-store/dnastack-client-library:$(git describe)"
    docker push gcr.io/dnastack-pub-container-store/dnastack-client-library:latest
popd || exit

pushd docker/dnastack-cli || exit
    docker build --no-cache -t "gcr.io/dnastack-pub-container-store/dnastack-cli:$(git describe)" .
    docker tag "gcr.io/dnastack-pub-container-store/dnastack-cli:$(git describe)" gcr.io/dnastack-pub-container-store/dnastack-cli:latest
    docker push "gcr.io/dnastack-pub-container-store/dnastack-cli:$(git describe)"
    docker push gcr.io/dnastack-pub-container-store/dnastack-cli:latest
popd || exit