#!/usr/bin/env bash


pushd docker/dnastack-clippe || exit
    docker build -t "gcr.io/dnastack-pub-container-store/clippe:$(git describe)" .
    docker tag "gcr.io/dnastack-pub-container-store/clippe:$(git describe)" gcr.io/dnastack-pub-container-store/clippe:latest
    docker push "gcr.io/dnastack-pub-container-store/clippe:$(git describe)"
    docker push gcr.io/dnastack-pub-container-store/clippe:latest
popd || exit
